"use strict";
/* lang-logic.js — logic.js game-data strings EN dictionary fragment. Keys = Chinese data text; values = natural English. First-wins merge into window.__EN. */
(function () {
  const EN = (window.__EN = window.__EN || {});
  const FRAG = {
    "一切都在失控边缘": "Everything teeters on the edge of losing control",
    "一半的意识总在别处漫游，清醒时也像在做梦；对精神层面的冲击更有抵抗力。": "Half your mind always wanders elsewhere; even awake you feel like you're dreaming. You resist mental strikes more easily.",
    "一方强者，能改变局部环境": "A strong one in their domain, able to reshape the local environment",
    "万念成真": "Thoughts become real",
    "万物失重": "Everything weightless",
    "万用，可仪式放大，可传承": "Versatile, amplifiable through ritual, and inheritable",
    "不可控，会侵蚀使用者": "Uncontrollable; it erodes the user",
    "不死者": "Immortal",
    "与某个概念绑定，近乎设定级的存在": "Bound to a concept; nearly setting-level existence",
    "与某个概念订立契约后获得的规则级力量。强得近乎不讲理，但必须遵守戒律。": "Rule-level power gained by contracting with a concept. Strong almost beyond reason, but its doctrines must be obeyed.",
    "与概念订立的誓约": "A vow sworn to a concept",
    "与身体绑定的天赋": "A talent bound to the flesh",
    "严格守恒": "Strictly conserved",
    "中立": "Neutral",
    "亲人": "Kin",
    "仇人": "Enemy",
    "以符文、咒式与仪式操作外部灵能。可学习、可传承，靠结构与准备取胜。": "Manipulates external psionics through runes, incantations and rituals. Learnable and inheritable; wins through structure and preparation.",
    "以誓约换来的概念级权柄": "Concept-level authority traded for an oath",
    "以金属、陶瓷或魔像材料构成的躯壳，核心处有一枚驱动结构，无需进食与呼吸。": "A shell of metal, ceramic or golem materials with a driving core inside. Needs no food or air.",
    "低重力与灵风之海": "A sea of low gravity and psionic wind",
    "体内寄居着一个未被收容的异常，它偶尔会在你的肋骨间翻个身。": "An uncontained anomaly dwells within you; sometimes it turns over between your ribs.",
    "体力、精神，过载时透支健康": "Stamina and resolve; overdraw on health when overloaded",
    "体魄": "Body",
    "佣兵团": "Mercenary company",
    "信息": "Information",
    "债务": "Debt",
    "元素灵体": "Elemental spirit",
    "光影": "Light and shadow",
    "入门": "Initiate",
    "公会": "Guild",
    "共存互利": "Coexist and profit together",
    "共振": "Resonance",
    "内敛": "Reserved",
    "凝滞": "Stagnant",
    "几乎与现实无异，异常只藏在缝隙里": "Nearly identical to reality; anomaly hides only in the cracks",
    "几乎没有": "Almost none",
    "凭空生灭": "Forged from nothing",
    "刚触及能力，尚不稳定": "Just touched their power; still unstable",
    "初觉": "First awakening",
    "力量与耐久": "Strength and endurance",
    "半神": "Demigod",
    "单人足以扭转城区格局，触及时间与因果": "Alone enough to overturn a city district, reaching into time and causality",
    "危险的": "Dangerous",
    "即发即至，稳定可靠，不依赖环境": "Instant and reliable; doesn't depend on the environment",
    "友好": "Friendly",
    "受血腥与满月刺激时易失控（稳定度上限 −5）": "Easily loses control when goaded by bloodshed or the full moon (stability cap −5)",
    "受魔法伤害 ×1.2（灵能干扰）": "Takes ×1.2 magic damage (psionic interference)",
    "古兽血脉": "Ancient beast bloodline",
    "可改写": "Rewritable",
    "同僚": "Colleague",
    "同盟": "Ally",
    "命运锚点": "Fate anchor",
    "商会": "Merchants",
    "因果": "Causality",
    "因果与命运的刚性，权能与时间类能力的土壤": "The rigidity of causality and fate; soil for authority and time-based power",
    "因果回声": "Causal echo",
    "因果松弛": "Causality Relaxation",
    "因果松弛（越高越强）与心念显化": "Causality relaxation (stronger the higher) and mind manifestation",
    "在灵能枯竭的地方黯淡无力（稳定度上限 −5）": "Dim and powerless where psionics run dry (stability cap −5)",
    "地下组织": "Underworld",
    "均衡型": "Balanced",
    "域主": "Domain Lord",
    "外向性": "Extraversion",
    "外放": "Outgoing",
    "外表是普通人，灵魂上却刻着一份契约，对方的目光会在关键时刻落在你身上。": "Ordinary on the outside, but a contract is etched into your soul; their gaze lands on you at the crucial moment.",
    "外部灵能：灵脉、星象、契约物": "External psionics: ley lines, celestial signs, bound objects",
    "失重": "Weightless",
    "失重高地": "Weightless heights",
    "契约": "Contract",
    "契约方索取代价：每回合稳定度额外 −0.8": "The other party exacts a price: −0.8 stability per round",
    "契约缔结者": "Contract sworn",
    "好奇": "Curious",
    "存在感与统御力": "Presence and command",
    "存在感稀薄，生命上限 −10%": "Thin presence; health cap −10%",
    "存在易被「驱散」（稳定度侵蚀 ×1.25）": "Easily \"dispersed\" (stability erosion ×1.25)",
    "存在稳定度 + 记忆 + 身体畸变": "Existential stability + memory + body mutation",
    "学得而来的结构化技艺": "A structured art learned by study",
    "学派学院": "Academy",
    "学者": "Scholar",
    "守护者": "Guardian",
    "守旧": "Set in their ways",
    "宗师": "Master",
    "官方机构": "Official body",
    "宜人性": "Agreeableness",
    "宿敌": "Nemesis",
    "对灵能类攻击更脆弱（魔法伤害 ×1.15）": "More fragile against psionic attacks (magic damage ×1.15)",
    "寿命、名字、情感，或一件重要的东西": "Lifespan, name, emotions, or something dear",
    "尖锐": "Sharp",
    "尽责性": "Conscientiousness",
    "崇拜献祭": "Worship and sacrifice",
    "师徒": "Mentor and apprentice",
    "常识世界": "A common-sense world",
    "平直": "Flat",
    "开放性": "Openness",
    "异化畸变体": "Aberrant mutant",
    "异常": "Anomaly",
    "异常寄居者": "Anomaly host",
    "异常有自己的「收容规则」，必须遵守": "The anomaly has its own \"containment rules\", and they must be followed",
    "异常浓度": "Anomaly Density",
    "异常浓度（越浓越强，反噬与环境侵蚀也越高）": "Anomaly density (stronger when thicker, but backlash and environmental erosion rise too)",
    "引力": "Gravity",
    "影响整片区域的现实结构": "Alters the reality structure of an entire region",
    "循环之城": "City of loops",
    "微弱": "Faint",
    "心念显化": "Mind Manifestation",
    "心念显化（越高越强）与因果松弛": "Mind manifestation (stronger the higher) and causality relaxation",
    "心相深渊": "Mind abyss",
    "心象具现": "Mind-image projection",
    "心跳早已停止，躯体靠某种残留的意志维系；伤口愈合得很慢，却几乎不会腐坏。": "Your heartbeat long since stopped; the body is held together by a lingering will. Wounds heal slowly, yet it barely ever rots.",
    "必须遵守戒律，破戒即失效": "Doctrines must be obeyed; break one and it fails",
    "恋人": "Lover",
    "情绪敏感": "Emotionally sensitive",
    "意志": "Will",
    "意志与信念影响现实的程度，超能力的土壤": "How strongly will and conviction shape reality; the soil of superpowers",
    "意志与魅力": "Will and charisma",
    "意念在此成形。想到什么，就会遇见什么。": "Thought takes shape here. Think of something and you will meet it.",
    "意识塑造现实": "Consciousness shapes reality",
    "感知": "Perception",
    "感知与意志": "Perception and will",
    "慢，依赖环境灵能，可被打断": "Slow, reliant on ambient psionics, and can be interrupted",
    "成员": "Member",
    "戒律可被利用，领域外受限": "Doctrines can be exploited; power is limited outside their domain",
    "战斗技": "Combat technique",
    "扭曲": "Distorted",
    "拟态体": "Mimic",
    "拥有自己的「领域」，局部改写法则": "Has its own \"domain\" that rewrites local laws",
    "挚友": "Bosom friend",
    "推理与术式理解": "Reasoning and grasp of spellcraft",
    "收容失效": "Containment breach",
    "收容失效，异常泛滥": "Containment breached, anomaly flooding loose",
    "收容封存": "Sealed in containment",
    "敌对": "Hostile",
    "敏感": "Sensitive",
    "敏捷": "Agility",
    "教团": "Cult",
    "无感": "Imperceptible",
    "无视回避": "Ignores evasion",
    "无视常规防御，规则级手段": "Ignores conventional defenses; a rule-level means",
    "时痕者": "Time-scarred",
    "时间": "Time",
    "时间凝滞": "Time congeals",
    "时间在此打结，因果可以被改写，代价是自己的过去。": "Time knots here; causality can be rewritten, at the price of your own past.",
    "时间奔流": "Time races onward",
    "时间流速": "Time Flow",
    "时间环与命运锚点": "Time loops and fate anchors",
    "时间遗迹": "Time ruin",
    "明显的": "Evident",
    "星裔": "Starborn",
    "显著": "Marked",
    "显著异常": "Marked anomaly",
    "智识": "Intellect",
    "术式师": "Spellwright",
    "权柄": "Authority",
    "权能": "Authority",
    "来自现实裂隙的渗透。力量强大却不可完全驾驭，使用者本身会被慢慢改写。": "An infiltration from rifts in reality. Powerful but never fully tame; the user is slowly rewritten.",
    "构装人": "Construct",
    "枢纽": "Hub",
    "枯竭": "Depleted",
    "核心能力": "Core ability",
    "梦境": "Dream",
    "梦渊": "Dream abyss",
    "梦行者": "Dreamwalker",
    "概念": "Concept",
    "概念残响": "Concept echo",
    "概念覆写，对所有体系都占优": "Concept overwrite; has the edge over every system",
    "死敌": "Mortal enemy",
    "沉稳": "Composed",
    "没有固定的形态，能在短时间内模仿他人的轮廓；真正的样子连自己也记不太清。": "No fixed form; can mimic another's silhouette for a short while. Even you barely recall your true shape.",
    "法则崩坏边缘": "Edge of law collapse",
    "泛滥": "Overflowing",
    "洞察与对异常的敏感": "Insight and sensitivity to the anomalous",
    "浓烈": "Intense",
    "浮空群岛": "Floating isles",
    "混沌熔炉": "Chaos crucible",
    "渗流": "Seepage",
    "渗漏": "Seeping",
    "温和": "Gentle",
    "源自自身生物场与意志的先天能力。直接、迅速、不依赖外物，但主题单一且有上限。": "Innate power born of your own biofield and will. Direct, fast, independent of outside tools, but single-themed and capped.",
    "潜行者": "Stalker",
    "灵晶结出": "Psionic crystal bloom",
    "灵潮涨落": "Psionic tides rise and fall",
    "灵潮都市": "Tide-touched city",
    "灵能": "Psionics",
    "灵能 + 咏唱时间 + 媒介": "Psionics + chanting time + medium",
    "灵能与异常都被抽干的死地，魔法在这里几乎失效。": "A dead land drained of both psionics and anomaly; magic barely works here.",
    "灵能乱流：灵能过载或枯竭都会反噬": "Psionic turbulence: overload or exhaustion both backfire",
    "灵能枯竭时迅速衰弱（稳定度上限 −10）": "Fades fast where psionics run dry (stability cap −10)",
    "灵能浓度": "Psionic Density",
    "灵能浓度（约 55 最稳，过高过低都增加反噬）": "Psionic density (most stable around 55; too high or low raises backlash)",
    "灵能荒漠": "Psionic wasteland",
    "灵脉交汇之处，魔法在这里格外顺手，也格外危险。": "A meeting of ley lines; magic flows especially well here, and especially dangerously.",
    "灵脉圣地": "Ley-line sanctuary",
    "灵血后裔": "Psionic-blood lineage",
    "灾厄": "Calamity",
    "灾难级的": "Catastrophic",
    "熔炉": "Crucible",
    "熟练": "Skilled",
    "熵律松弛": "Entropy Relaxation",
    "物质": "Matter",
    "猎杀清除": "Hunt and purge",
    "现实在此开裂，异常以此为巢，空间也不再可靠。": "Reality splits open here; anomaly nests in the gap and space is no longer reliable.",
    "现实排斥：稳定度过低会被世界抹去": "Reality rejection: let stability run too low and the world erases you",
    "现实裂隙": "Reality rift",
    "现实裂隙、异常实体、被污染的物件": "Reality rifts, anomalous entities, fouled objects",
    "现实裂隙与异常实体的密度": "Density of reality rifts and anomalous entities",
    "生命": "Health",
    "生命域能力对你反向起效（受到 ×1.25）": "Life-domain powers work against you (you take ×1.25)",
    "生死": "Life and death",
    "生长": "Growth",
    "由某个被遗忘的概念凝成的存在，人们记不住你的样貌，只记得你留下的感觉。": "An existence condensed from a forgotten concept; people can't recall your face, only the feeling you leave.",
    "盟友": "Ally",
    "相对标准时间的流逝速度": "Rate at which time passes relative to standard",
    "相识": "Acquaintance",
    "研究会": "Research institute",
    "研究利用": "Study and exploit",
    "破戒：违背誓约会失去权能，甚至失去自我": "Broken oath: violate the vow, lose your authority, even lose yourself",
    "秩序稳定、人口密集，异常被压低，交易与情报汇聚于此。": "Stable order, dense population; anomaly held down while trade and intelligence gather here.",
    "移动方式、建筑与生态的基本形态": "Basic form of movement, architecture and ecology",
    "稳固": "Stable",
    "稳定度上限低，外貌令社交受阻": "Low stability cap; your looks hamper social dealings",
    "稳定度低时，体内的东西可能夺取控制": "When stability runs low, what dwells within may seize control",
    "空间": "Space",
    "空间褶皱": "Space Distortion",
    "突击者": "Striker",
    "竞争对手": "Rival",
    "精力": "Energy",
    "精神": "Mind",
    "精神强度与稳定度": "Mental strength and stability",
    "精锐": "Elite",
    "组织里的骨干，可对抗小型异常": "A core member of the organization, able to face minor anomalies",
    "经过加固的据点，规则稳固，异常难以渗入。": "A reinforced stronghold; rules hold firm and anomaly struggles to seep in.",
    "统御者": "Commander",
    "聚落联盟": "Settlement league",
    "肉体脆弱，缺乏先天抗性": "Frail flesh, lacking innate resistance",
    "能力主题单一，射程与强度有天花板": "Single-themed power; hard ceilings on range and strength",
    "能力暴走：精力见底时最危险": "Power runaway: most dangerous when energy runs dry",
    "能可靠地使用单一能力": "Can wield a single ability reliably",
    "能组合技巧，足以对付数名常人": "Can combine techniques; enough to handle several ordinary folk",
    "能量": "Energy",
    "能量凭空涌现，热力学在这里只是建议。": "Energy wells up from nothing; thermodynamics is only a suggestion here.",
    "能量守恒与热力学定律的约束力": "How tightly the conservation of energy and the laws of thermodynamics bind",
    "能量涌现": "Energy surge",
    "自律": "Self-disciplined",
    "自我认同薄弱（稳定度上限 −10）": "Weak sense of self (stability cap −10)",
    "自身的生物场与意志": "Your own biofield and will",
    "虚无": "Nothingness",
    "虚空裔": "Voidborn",
    "血液里流着稀薄的灵能，心脏搏动时会泛出微光；骨骼比常人更轻。": "Thin psionics run in your blood and your heart glows faintly with each beat; your bones are lighter than most.",
    "血肉之躯，构造与常人无异，但神经系统对异常刺激格外敏感。": "Flesh and blood built like anyone else, but your nervous system is unusually sensitive to anomaly.",
    "血脉里混着星辰的碎屑，夜里皮肤会浮起细小的星点；对光与引力格外敏感。": "Stardust runs in your bloodline; at night fine star-flecks rise on your skin. Keenly sensitive to light and gravity.",
    "被动": "Passive",
    "被污染而生的不可控之力": "An uncontrollable power born of contamination",
    "裂隙区": "Rift zone",
    "裂隙荒原": "Rift wasteland",
    "要塞": "Fortress",
    "见习": "Apprentice",
    "觉醒人类": "Awakened human",
    "记忆错位（稳定度上限 −8）": "Displaced memories (stability cap −8)",
    "超能力": "Superpower",
    "距离与方向的可靠程度": "How reliable distance and direction remain",
    "距离崩坏": "Distance collapse",
    "身体中央有一处「空」，光线与视线都会被它悄悄吞掉；你更像一个洞，而不是一个人。": "A \"void\" sits at your center, quietly swallowing light and gaze. You are more a hole than a person.",
    "身体由半凝聚的能量或元素构成，轮廓会在情绪波动时模糊、流动。": "Your body is half-condensed energy or element; your outline blurs and flows when emotions surge.",
    "身体的一部分已被异常改写：骨骼、皮肤或器官发生了不可逆的重构。": "Part of your body has been rewritten by anomaly: bone, skin or organs irreversibly remade.",
    "身体的一部分被困在别的时间里：一只手比另一只年长，或者影子比你慢了半拍。": "Part of your body is trapped in another time: one hand older than the other, or a shadow that lags half a beat behind.",
    "身体羸弱，缺乏防护（防御 −1.5）": "Weak body, little protection (defense −1.5)",
    "轻微异常": "Minor anomaly",
    "轻微的": "Minor",
    "辅助技": "Support technique",
    "速度与反应": "Speed and reflexes",
    "造物": "Creation",
    "道路与航线交汇之处，各路人马往来，消息灵通。": "Where roads and shipping lanes meet; all kinds of folk pass through and word travels fast.",
    "都会": "Metropolis",
    "重力场": "Gravity Field",
    "重力沉重得让人喘不过气，深处埋着被压缩的东西。": "Gravity bears down until you can't breathe; something compressed lies buried in the depths.",
    "重力稀薄，岩石与人一同漂浮，适合擅长机动的人。": "Gravity is thin; rock and people float alike. Ground for those who live by movement.",
    "重压": "Crushing Pressure",
    "重压之世": "A world of crushing pressure",
    "重压深坑": "Crushing depth",
    "铁律": "Ironclad law",
    "随性": "Easygoing",
    "集体梦境": "Collective dream",
    "需要符文、咏唱或媒介，准备越久越强": "Needs runes, chanting or a medium; the longer the preparation, the stronger the effect",
    "静默荒原": "Silent wasteland",
    "非欧街区": "Non-Euclidean quarter",
    "题材狭窄，受情绪影响，可被抑制": "Narrow theme, swayed by mood, can be suppressed",
    "飞逝": "Racing",
    "首领": "Leader",
    "骨干": "Core",
    "骨骼与肌腱带着兽类的比例，感官锐利，指甲与牙齿比常人更硬。": "Bone and sinew carry a beast's proportions; senses keen; nails and teeth harder than a human's.",
    "高危异常": "High-risk anomaly",
    "魅力": "Charisma",
    "魔法": "Magic",
    "魔法复苏的现代都市": "A modern city where magic has awoken anew",
    "魔法的燃料，也是失控的源头": "Magic's fuel, and the source of its loss of control",
  };
  for (const k in FRAG) if (!(k in EN)) EN[k] = FRAG[k];
})();
