"use strict";
/* lang-body.js — body.html 静态文本的英文词典片段（由 i18n 任务代理填充）。
   格式：Object.assign(window.__EN, { '中文': 'English', ... })。重复键不覆盖。 */
(function () {
  const EN = (window.__EN = window.__EN || {});
  const FRAG = {
    "跳到内容": "Skip to content",
    "万象工坊": "Realm Forge",
    "工坊分区": "Workshop sections",
    "体系总览": "Overview",
    "世界法则": "World Laws",
    "地图地点": "Map & Locations",
    "势力关系": "Factions",
    "角色工坊": "Character Forge",
    "远征": "Expedition",
    "推演": "Simulation",
    "前往世界法则": "Go to World Laws",
    "当前世界": "Current world",
    "违常指数": "Anomaly index",
    "先调法则，再造人物，最后让他们碰撞。": "Shape the laws, forge the people, then let them collide.",
    "万象工坊是一个可以改写物理定律的沙盒。世界由八个法则旋钮定义，地图上的每个地点还能局部改写它们；魔法、异常、超能力与权能都要付出代价；角色属于势力、彼此之间有恩怨。派一支队伍去远征，他们会在行军中遭遇事件、在战争里改变领土，并随着经历真正成长。": "Realm Forge is a sandbox where the laws of physics can be rewritten. A world is defined by eight law dials, and each place on the map can partly rewrite them as well. Magic, anomaly, superpowers and authority all demand a price. Characters belong to factions and hold grudges against one another. Send a party on an expedition — they will run into events while marching, change territory in war, and truly grow through experience.",
    "点一个世界模板，雷达图会跟着变化。": "Pick a world template and the radar chart follows.",
    "调整这个世界": "Tune this world",
    "直接创建角色": "Create a character directly",
    "红色 = 偏离常识物理的部分": "Red = deviation from the physics we know",
    "八层结构": "The Eight Layers",
    "上一层的输出，是下一层的输入。你可以只玩其中一层，也可以让八层一起运转，让一支队伍真正在这个世界里活一遍。": "Each layer's output feeds the next. Play just one layer, or set all eight in motion and let a party truly live out a life in this world.",
    "法则层": "Law Layer",
    "八个旋钮改写世界：重力、时间、空间、熵律、灵能、异常、因果、心念。它们共同输出「违常指数」、各体系的效率修正，以及这个世界里会发生的异象。": "Eight dials rewrite the world: gravity, time, space, entropy, psionics, anomaly, causality and mind. Together they produce the anomaly index, efficiency modifiers for each system, and the phenomena that will occur in this world.",
    "空间层": "Space Layer",
    "地图由地点与路线组成。每个地点是一种类型（都会、灵脉圣地、裂隙区、时间遗迹……），会在世界旋钮之上再叠加一层局部偏移，所以同一个世界里，相隔一条路线就可能是另一套物理。": "The map is made of locations and routes. Each location has a type (metropolis, ley-line sanctuary, rift zone, time ruin...), and stacks a local offset on top of the world dials — so in the same world, one route apart can mean a different set of physics.",
    "体系层": "System Layer",
    "魔法、异常、超能力、权能四套能力逻辑。每一套都必须回答四个问题：力量从哪来？付出什么？受什么限制？失控会怎样？": "Four ability systems: magic, anomaly, superpowers and authority. Each must answer four questions: where does the power come from, what does it cost, what limits it, and what happens when it spirals out of control?",
    "能力层": "Ability Layer",
    "能力 = 域 × 效果 × 形态 × 触发 × 代价 × 限制。十八个域（物质到虚无）由位阶逐步解锁，十种效果自由组合，因此能生成的能力几乎不会重复。": "Ability = domain × effect × form × trigger × cost × limit. Eighteen domains (from matter to nothingness) unlock with tier, and ten effects combine freely, so generated abilities almost never repeat.",
    "角色层": "Character Layer",
    "十五种出身决定身体构造与先天特质；六维属性按位阶预算分配；五维性格生成阵营与言行习惯；外观带着能力显现出来的「异象特征」。": "Fifteen origins decide body structure and innate traits; six attributes are budgeted by tier; five personality axes generate alignment and habits; and appearance carries the anomaly traits where abilities manifest.",
    "社会层": "Society Layer",
    "角色隶属于势力，势力之间有同盟与死敌，角色之间有亲人、宿敌与债务。势力会自行宣战、媾和、扩张与衰落，地图上的地点会因此易主——这一切在后台随时间持续演化，不需要玩家推动。": "Characters belong to factions; factions form alliances and mortal enemies; characters have kin, nemeses and debts. Factions declare war, make peace, expand and decline on their own, and map locations change hands as a result — all of it evolving in the background over time, without the player pushing it.",
    "成长层": "Growth Layer",
    "角色在远征与战斗中获得经验，位阶提升时按这段经历的侧重分配属性点，位阶跨过门槛时能力还会进化出新的形态。经历会留下烙印与个人史，性格也可能被漫长的旅途悄悄改变。": "Characters gain experience through expeditions and combat. On rising a tier, attribute points are allocated toward what the stretch emphasized, and crossing thresholds can evolve abilities into new forms. Experience leaves marks and personal history, and a long journey may quietly reshape personality.",
    "推演层": "Simulation Layer",
    "回合制对抗，支持单挑与最多 5 对 5 的小队战，可以指定战场地点，再用蒙特卡洛估算胜率；远征标签页则是同一套引擎的持续版本——每一次行军、每一场遭遇战都在真正修改角色与世界。": "Turn-based combat supporting duels and squad battles up to 5v5. Pick a battlefield, then estimate win rates with Monte Carlo. The Expedition tab is the persistent version of the same engine — every march and every skirmish truly modifies characters and the world.",
    "四条设计准则": "Four Design Principles",
    "违常必有价": "Anomaly Always Has a Price",
    "任何违背常规物理的能力，都要同时声明代价、限制与弱点。没有代价的力量，只会让故事失去张力。": "Any ability that breaks conventional physics must declare its cost, limits and weaknesses. Power without a price only drains tension from the story.",
    "世界定上限，角色定形状": "The World Sets the Ceiling, the Character the Shape",
    "同一个能力，在灵潮都市与灵能荒漠里的强度可以相差三倍。世界决定「能不能」，角色决定「怎么用」。": "The same ability can be three times stronger in a tide-touched city than in a psionic wasteland. The world decides whether it can happen; the character decides how it is used.",
    "体系互相克制": "Systems Counter Each Other",
    "魔法克异常，异常克超能力，超能力克魔法；权能凌驾其上，却被自己的戒律束缚。没有绝对的强者。": "Magic beats anomaly, anomaly beats superpower, superpower beats magic; authority towers above all yet is bound by its own decrees. There is no absolute strongest.",
    "稳定度是第二条命": "Stability Is a Second Life",
    "精神、信息、概念类攻击与异常侵蚀会消耗稳定度。生命归零是死亡，稳定度归零是被现实抹去。": "Mental, information and concept attacks, plus anomaly erosion, consume stability. Health at zero is death; stability at zero is being erased from reality.",
    "四大能力体系": "The Four Ability Systems",
    "体系克制关系": "System Counter Triangle",
    "箭头指向被克制的一方": "Arrows point at the side being countered",
    "克制方威力 ×1.25，被克制方 ×0.8。权能对三者都是 ×1.15，反过来被它们攻击时只受 ×0.9，但权能会以一定概率违背戒律而遭到反噬。": "The countering side deals ×1.25, the countered side ×0.8. Authority deals ×1.15 against all three but takes only ×0.9 from them — yet authority may violate its decrees and suffer backlash.",
    "位阶": "Tier",
    "规则速查": "Quick Reference",
    "展开公式与判定细节": "Expand formulas and resolution details",
    "属性预算": "Attribute budget",
    "总点数 = 42 + 6 × 位阶；每项 1 至 20（随机生成时不低于 3）。超支的每一点会让稳定度上限 −2。最终属性 = 分配值 + 出身修正（1 至 24）。": "Total points = 42 + 6 × tier; each stat 1–20 (no less than 3 when rolled). Every point over budget lowers stability cap by −2. Final stat = allocated + origin modifier (1 to 24).",
    "生命": "Health",
    "30 + 体魄 × 5 + 意志 × 2 + 位阶 × 12": "30 + Body × 5 + Will × 2 + tier × 12",
    "体系资源": "System resource",
    "20 + 意志 × 3 + 智识 × 2 + 位阶 × 8。魔法称灵能，异常称渗流，超能力称精力，权能称权柄。": "20 + Will × 3 + Intellect × 2 + tier × 8. Magic calls it psionics, anomaly seepage, superpower energy, authority authority.",
    "稳定度": "Stability",
    "40 + 意志 × 3 + 感知 + 出身与被动修正，最低 20。": "40 + Will × 3 + Perception + origin and passive modifiers, minimum 20.",
    "核心能力威力": "Core ability power",
    "8 + 位阶 × 2.2 + 主属性 × 1.1。战斗技为其 75%，消耗为核心的 40%。": "8 + tier × 2.2 + primary stat × 1.1. Combat techniques deal 75% of it and cost 40% of the core.",
    "命中": "Hit chance",
    "85% + 敏捷差 × 1.5% + 感知差 × 0.5% − 对方闪避，限制在 40% 至 97%。敏捷会被重力偏离削弱最多 25%。": "85% + Agility gap × 1.5% + Perception gap × 0.5% − target evasion, capped at 40% to 97%. Agility is weakened up to 25% by gravity deviation.",
    "伤害": "Damage",
    "基础值 × 世界修正 × 出身加成 × 体系克制 × 抗性 × 随机(0.88 至 1.12) × 暴击(1.5)，再减去防御的 60%（异常技能只减 30%）。": "Base × world modifier × origin bonus × system counter × resistance × random(0.88–1.12) × crit(1.5), then minus 60% of defense (anomaly skills reduce only 30%).",
    "稳定度伤害": "Stability damage",
    "精神、信息、概念域的技能造成伤害的 25% 稳定度伤害；异常体系再加 15%。": "Mental, information and concept domain skills deal 25% of their damage as stability damage; the anomaly system adds another 15%.",
    "因果偏转": "Fate deflection",
    "每次攻击有 因果松弛 × 15% 的概率被命运接管：必定暴击或必定落空。": "Each attack has a causality-looseness × 15% chance of being seized by fate: guaranteed crit or guaranteed miss.",
    "反噬": "Backlash",
    "魔法在灵能偏离 55 越远越易反噬；异常随异常浓度与空间褶皱上升；超能力在精力低于 25% 时暴走；权能视因果松弛而定。": "Magic backlashes more the further psionic deviation is from 55; anomaly rises with anomaly concentration and spatial folds; superpower runs wild below 25% energy; authority depends on causality looseness.",
    "局部法则": "Local laws",
    "地点的实际旋钮 = 世界旋钮 + 该地点的偏移（限制在 0 至 100）。在某地推演时，一切世界修正都按这里的数值计算。": "A location's effective dials = world dials + its offset (capped 0–100). When simulating somewhere, all world modifiers are computed from these values.",
    "小队默契": "Squad cohesion",
    "队友之间每一级正向关系 +2% 输出，每一级负向关系 −3%；同势力的队友每人 +2%。总修正限制在 ×0.85 至 ×1.15。": "Each positive relation level between allies gives +2% output, each negative level −3%; same-faction allies get +2% each. Total modifier capped at ×0.85–×1.15.",
    "宿怨与犹豫": "Grudges and hesitation",
    "对阵关系为负的对手，伤害 +4% 每级；对阵关系为正的对手，伤害 −4% 每级。": "Against an opponent with negative relation, damage +4% per level; positive relation, damage −4% per level.",
    "小队行动": "Squad actions",
    "按先攻排序依次行动。攻击优先选生命低、被自己克制、有仇的目标；辅助技能会去援助全队最虚弱的人。": "Act in initiative order. Attacks prefer low-health, countered or hated targets; support skills aid the party's weakest member.",
    "白热化": "Crescendo",
    "第 9 回合起，所有伤害每回合递增 7%，保证对局最终会分出胜负。": "From round 9 on, all damage rises 7% per round, guaranteeing the match eventually resolves.",
    "势力加成": "Faction bonus",
    "成员使用势力偏好的体系时，该体系威力 +5%。": "When a member uses the faction's preferred system, that system's power is +5%.",
    "晋升经验": "Promotion XP",
    "升到下一位阶所需经验 = 40 × 位阶 + 10 × 位阶²，晋升时获得 6 点属性分配点，按这段经历里各属性被「使用」的次数加权随机分配。": "XP needed for next tier = 40 × tier + 10 × tier². On promotion gain 6 attribute points, weighted randomly by how often each stat was \"used\" in that stretch.",
    "能力进化": "Ability evolution",
    "位阶每跨过一个新域的解锁门槛，有 40% 的概率让一项战斗技或辅助技进化为该新域的能力。": "Each time a tier crosses a new domain's unlock threshold, there is a 40% chance one combat or support technique evolves into that domain's ability.",
    "远征检定": "Expedition checks",
    "取队伍中该属性最高的两人（次高者打 25% 折扣）算出队伍分数，与事件难度比较：成功率 = 50% + (分数 − 难度) × 5%，限制在 8% 至 95% 之间。": "Take the two highest in that stat (second gets a 25% discount) for a party score, compare with event difficulty: success = 50% + (score − difficulty) × 5%, capped at 8%–95%.",
    "事件难度": "Event difficulty",
    "基础难度 = 8 + 2 × 队伍平均位阶 + 局部违常指数 ÷ 14，再按具体事件调整。": "Base difficulty = 8 + 2 × average party tier + local anomaly index ÷ 14, then adjusted per event.",
    "怎么玩": "How to Play",
    "调世界。": "Tune the world.",
    "选模板或拧旋钮，看违常指数与各体系的效率变化。": "Pick a template or turn the dials and watch the anomaly index and system efficiencies shift.",
    "画地图。": "Draw the map.",
    "生成一张区域地图，给每个地点选类型、指定控制势力，必要时微调局部偏移。": "Generate a regional map, give each location a type and a controlling faction, and fine-tune local offsets when needed.",
    "立势力。": "Found factions.",
    "编辑势力的理念与关系；点「一键生成群像」可以直接得到一批有归属、有恩怨的角色。": "Edit faction ideals and relations; hit \"Generate Cast\" to instantly get a batch of characters with allegiances and feuds.",
    "造角色。": "Forge characters.",
    "指定位阶、体系、出身与所属势力，或随机重铸；每一块内容都能单独重掷、手动微调。": "Set tier, system, origin and faction, or reroll randomly; every block can be re-rolled and manually fine-tuned on its own.",
    "做推演。": "Run simulations.",
    "选单挑或小队，选一个战场地点，看战报与胜率；换个地点，结果会完全不同。": "Choose a duel or a squad battle, pick a battlefield, and review the report and win rate; change the location and the outcome changes completely.",
    "去远征。": "Go on an expedition.",
    "挑几名角色组成远征队，在地图上行军。路上会遭遇事件、战斗、委托，世界也在后台继续打仗与扩张——回头再看，角色已经不是出发时的样子了。": "Pick a few characters into an expedition party and march across the map. Encounters, battles and quests await on the road, while the world keeps fighting and expanding in the background — look again and your characters are no longer who they were when they set out.",
    "世界档案": "World File",
    "选模板，或从头调": "Pick a template, or tune from scratch",
    "世界名称": "World name",
    "随机名": "Random name",
    "随机生成整个世界": "Generate a whole random world",
    "法则旋钮": "Law dials",
    "红线 = 与常识物理的偏离": "Red line = deviation from known physics",
    "违常读数": "Anomaly Reading",
    "体系效率": "System efficiency",
    "相对常态的威力倍率": "Power multiplier relative to baseline",
    "此世界的异象": "Phenomena of this world",
    "抽取一次世界事件": "Draw a world event",
    "区域地图": "Regional map",
    "点击选中，拖动可移动地点": "Click to select; drag to move locations",
    "按当前世界重新生成地图": "Regenerate map from current world",
    "新增地点": "Add location",
    "势力": "Factions",
    "新增势力": "Add faction",
    "一键生成群像": "Generate Cast",
    "「一键生成群像」会随机创建 8 名带有势力、驻地与关系的角色并加入名册，可以立刻拿去组队推演。": "\"Generate Cast\" randomly creates 8 characters with factions, posts and relations, adds them to the roster, and they're ready for squad simulations at once.",
    "关系网": "Relation Web",
    "点击节点，高亮它的关系": "Click a node to highlight its relations",
    "势力与角色关系网": "Faction & character relation web",
    "大圆 = 势力，小点 = 角色（颜色为体系）": "Big circle = faction, small dot = character (color = system)",
    "基本设定": "Basics",
    "改动会立刻反映在右侧角色卡": "Changes reflect instantly on the card to the right",
    "随机重铸全部": "Reroll Everything",
    "存入名册": "Save to Roster",
    "名字": "Name",
    "换一个": "Another",
    "能力体系": "Ability System",
    "所属势力": "Faction",
    "职级": "Rank",
    "六维属性": "Six Attributes",
    "重掷属性分配": "Reroll attribute allocation",
    "五维性格": "Five Personality Axes",
    "拖动后阵营与性格描述会跟着变": "Dragging updates alignment and personality text",
    "重掷性格与动机": "Reroll personality & motives",
    "其他内容": "Other Details",
    "逐块重掷，不影响别处": "Re-roll block by block, leaving the rest untouched",
    "重掷外观": "Reroll appearance",
    "重掷能力": "Reroll ability",
    "重掷背景": "Reroll background",
    "名册": "Roster",
    "导入与导出": "Import & Export",
    "导出会把整个名册变成一段文字，复制保存即可；把它粘贴回来并点击导入，就能恢复。": "Export turns the entire roster into text for you to copy and save; paste it back and click Import to restore it.",
    "在这里粘贴导入的内容，或点击导出后复制": "Paste import content here, or copy it after exporting",
    "导入": "Import",
    "组建远征队": "Form Expedition Party",
    "从名册中选人，指定出发地点": "Pick members from the roster and set a starting point",
    "远征会真正改变角色：他们在路上获得的经验、伤痕与经历都会保留下来，即使远征结束也不会消失。人数上限 6 人。": "Expeditions truly change characters: the experience, wounds and history gained along the way are kept even after the expedition ends. Party size limit: 6.",
    "开始远征": "Start Expedition",
    "补给": "Supplies",
    "遭遇": "Encounter",
    "行动": "Actions",
    "行军一旬": "March one week",
    "连续行军": "March continuously",
    "扎营（1 旬）": "Camp (1 week)",
    "等待（1 旬）": "Wait (1 week)",
    "等待 5 旬": "Wait 5 weeks",
    "远征队": "Party",
    "加入": "Add",
    "重新组队（重置远征）": "Reform Party (Reset Expedition)",
    "沿途地图": "Route Map",
    "点击地点前往": "Click a location to travel there",
    "远征地图": "Expedition map",
    "天下大势": "State of the World",
    "纪事": "Chronicle",
    "最近发生的事，包含战争与外交": "Recent events, including wars and diplomacy",
    "推演场地": "Simulation Arena",
    "推演模式": "Simulation mode",
    "单挑": "Duel",
    "小队对抗": "Squad battle",
    "开始推演": "Run Simulation",
    "换一个随机对手": "Reroll opponent",
    "去看地图": "View the map",
    "每次推演都会用新的随机数打一场完整的对局，并另外模拟数百场来估算胜率。": "Each simulation plays a full match with fresh random numbers, then simulates hundreds more to estimate the win rate.",
    "友好、同盟、亲近": "Friendly, allied, close",
    "敌对、死敌、仇怨": "Hostile, mortal enemies, grudges",
    "出身与身体构造": "Origin & Body",
    "定位": "Role",
    "驻地": "Base",
    "导出名册": "Export Roster",
    "出发地点": "Starting point",
    "目的地": "Destination",
  };
  for (const k in FRAG) if (!(k in EN)) EN[k] = FRAG[k];
})();
