"use strict";
/* lang-ui.js — ui.js display strings EN dictionary fragment. Keys = Chinese display text; values = natural English. First-wins merge into window.__EN. */
(function () {
  const EN = (window.__EN = window.__EN || {});
  const FRAG = {
    "{0}的印记": "{0}'s Mark",
    "主属性": "Primary stat",
    "乙方": "Side B",
    "乙方明显占优。": "Side B is clearly favored.",
    "乙方胜率": "Side B win rate",
    "习惯": "Habits",
    "代价": "Cost",
    "代价与弱点": "Costs & Weaknesses",
    "位阶": "Tier",
    "体系反噬": "System backlash",
    "体系效率为": "system efficiency is",
    "作为对手": "As opponent",
    "依赖旋钮": "Dependent dials",
    "先天特质": "Innate traits",
    "先攻": "Initiative",
    "入乙队": "Join Squad B",
    "入甲队": "Join Squad A",
    "全局世界": "Global world",
    "八个法则旋钮偏离常识物理的程度": "How far the eight law dials deviate from known physics",
    "六维属性雷达图": "Six-attribute radar chart",
    "共": "Total",
    "关系": "Relations",
    "内容无法解析，请确认粘贴完整": "Couldn't parse the content. Make sure the paste is complete.",
    "出身弱点": "Origin weakness",
    "出身特征": "Origin traits",
    "分配值 + 出身修正": "Allocated value + origin modifier",
    "删除": "Delete",
    "力量来源": "Source of power",
    "势力与驻地": "Faction & Base",
    "双方势均力敌，未分胜负。": "Both sides are evenly matched; no clear winner.",
    "双方生存率随回合变化的折线图": "Line chart of both sides' survival rates by round",
    "反噬率": "Backlash rate",
    "取生命与稳定度中较低者，越接近 0 越接近倒下": "Take the lower of Health and Stability; the closer to 0, the closer to collapse",
    "同一世界、同样的双方，另外模拟 300 场": "Same world, same sides, 300 extra simulations",
    "名册已满（30 个），请先删除一些": "Roster is full (30). Delete some first.",
    "名册还是空的。创建一个喜欢的角色后点「存入名册」，或到「势力关系」页一键生成群像。": "The roster is empty. Create a character you like and hit \"Save to Roster\", or go to the Factions page and hit \"Generate Cast\".",
    "回合": "Round",
    "回合分出胜负": "Round settles the match",
    "回合耗尽，按剩余状态判定。": "Rounds run out; decided by remaining state.",
    "因果偏转": "Causal twist",
    "在": "At",
    "域": "Domain",
    "域 × 效果 × 形态": "Domain × Effect × Form",
    "外观": "Look",
    "大致含义": "General meaning",
    "失控": "Out of control",
    "对三者 ×1.15，受戒律约束": "×1.15 against all three, bound by doctrine",
    "小队最多 5 人，队员是加入时的快照。队友之间的关系会带来默契或拖累，宿敌之间会互相多打几分；关系可以在「势力关系」页编辑。": "Squads hold up to 5; members are a snapshot taken when they join. Relations between teammates bring cohesion or slow each other down, and nemeses hit each other harder. Relations can be edited on the Factions page.",
    "属性": "Attribute",
    "已分配": "Allocated",
    "已删除": "Deleted",
    "已存入名册": "Saved to roster",
    "已导入 {0} 个角色": "Imported {0} characters",
    "已换了一个随机对手": "Rerolled a new random opponent",
    "已更新名册中的这个角色": "Updated this character in the roster",
    "已生成导出内容，请复制保存": "Export content generated. Copy and save it.",
    "已载入：": "Loaded:",
    "平均": "Average",
    "平局": "Draw",
    "异化度": "Aberration",
    "异象浓度": "Anomaly density",
    "异象特征": "Anomaly traits",
    "弱点": "Weakness",
    "当前工坊角色": "Current forge character",
    "性格": "Personality",
    "戒律": "Doctrine",
    "战力": "Combat power",
    "战场": "Battlefield",
    "战报": "Battle report",
    "无": "None",
    "有": "Yes",
    "未命名世界": "Unnamed world",
    "本世界中的体系效率": "System efficiency in this world",
    "机动修正": "Mobility modifier",
    "权能": "Authority",
    "构造与出身": "Form & Origin",
    "核心动机": "Core motive",
    "此处体系效率": "Local system efficiency",
    "每次推演都会用新的随机数打一场完整的对局，并另外模拟数百场来估算胜率。": "Each simulation plays one full match with fresh random numbers, then runs hundreds more to estimate the win rate.",
    "没有识别到可导入的角色": "No importable characters recognized",
    "物理常数": "Physical constants",
    "环境侵蚀": "Environmental erosion",
    "环境侵蚀每回合": "Environmental erosion per round",
    "环境对这种力量的影响有限。": "The environment has limited effect on this power.",
    "生命": "Health",
    "生存率曲线": "Survival curve",
    "甲方": "Side A",
    "甲方明显占优。": "Side A is clearly favored.",
    "甲方胜率": "Side A win rate",
    "目前没有明显的异象，这是一个平静得有点无聊的世界。": "No notable anomalies right now. A world so calm it's a little dull.",
    "短板": "Weak point",
    "种子": "Seed",
    "称谓": "Title",
    "稳定度": "Stability",
    "稳定度/回合": "Stability per round",
    "稳定度上限": "Stability cap",
    "组好两支小队后点「开始推演」。": "Form two squads, then hit \"Run Simulation\".",
    "综合战力": "Overall combat power",
    "缺陷": "Flaws",
    "背景": "Background",
    "胜率估算": "Win-rate estimate",
    "能力": "Ability",
    "能力会在身体上留下痕迹": "Abilities leave marks on the body",
    "获胜": "Wins",
    "蓝线为甲方行动，红线为乙方行动": "Blue line is Side A's actions, red line is Side B's actions",
    "被动": "Passive",
    "角色卡": "Character card",
    "解锁的能力域": "Unlocked ability domains",
    "触发方式": "Trigger",
    "说话方式": "Way of speaking",
    "败者的生命耗尽。": "The loser's Health is spent.",
    "败者的稳定度耗尽，被现实抹去。": "The loser's Stability runs out and they are erased from reality.",
    "资源名为": "The resource is called",
    "超支": "Over budget",
    "身体构造": "Body structure",
    "载入": "Load",
    "这是一场势均力敌的对局。": "A closely matched contest.",
    "这里几乎是为这种力量准备的土壤。": "This place is almost made for this power.",
    "这里的规则在压制这种力量。": "The rules here suppress this power.",
    "违常": "Anomaly",
    "违常必有价": "Aberration always has a price",
    "违常指数": "Anomaly Index",
    "选好双方后点「开始推演」。": "Choose both sides, then hit \"Run Simulation\".",
    "重力与时间以 50 为常态，其余以 0 为常态；偏离越远，世界越不正常。": "Gravity and time default to 50; the rest default to 0. The further the deviation, the stranger the world.",
    "长处": "Strengths",
    "防御": "Defense",
    "阶": "Tier stage",
    "限制": "Limit",
    "随机对手": "Random opponent",
    "雷达图": "Radar chart",
    "项生效": "items active",
    "驱动魔法、异常、超能力与权能的世界级燃料。": "The world-scale fuel that drives magic, anomaly, superpower and authority.",
    "驻于": "Stationed at",
    "魔法克制异常，异常克制超能力，超能力克制魔法，权能位于中央": "Magic counters anomaly, anomaly counters superpower, superpower counters magic; authority sits at the center",
    "（沿用已解锁的域）": "(keeps unlocked domains)",
    "（违背即失效）": "(fails once violated)",
    "，基本无碍": ", mostly harmless",
    "，已相当严重": ", already quite severe",
    "，有可见的改变": ", a visible change",
    "重力": "Gravity",
    "时间": "Time",
    "空间": "Space",
    "熵律": "Entropy",
    "灵能": "Psionics",
    "异常": "Anomaly",
    "因果": "Causality",
    "心念": "Mind",
    "，": ", ",
    "在「{0}」中，{1}体系效率为 <b>×{2}</b>，环境侵蚀每回合 −{3} 稳定度。{4}": "In \"{0}\", the {1} system efficiency is <b>×{2}</b>; environmental erosion is −{3} stability per round. {4}",
    "{0}，资源名为「{1}」": "{0}; its resource is called \"{1}\"",
    "、": ", ",
    "　": " ",
    "：": ": ",
    "；": "; ",
    "（": " (",
    "）": ") ",
    "。": ".",
  };
  for (const k in FRAG) if (!(k in EN)) EN[k] = FRAG[k];
})();
