"use strict";
/* lang-ui3.js — ui3.js display strings EN dictionary fragment. Keys = Chinese display text; values = natural English. First-wins merge into window.__EN. */
(function () {
  const EN = (window.__EN = window.__EN || {});
  const FRAG = {
    "{0} 人，平均位阶 {1}，平均生命 {2}%": "{0} people, avg tier {1}, avg health {2}%",
    "{0} 场战争进行中": "{0} wars in progress",
    "位阶": "Tier",
    "先处理眼下的遭遇": "Handle the current encounter first",
    "到不了那里：中间没有连通的路线": "Can't get there: no connected route between",
    "前往": "Travel",
    "加入": "Add",
    "加入新成员…": "Add new member…",
    "名册是空的": "The roster is empty",
    "名册还是空的：先到「角色工坊」创建角色，或到「势力关系」页一键生成群像。": "The roster is still empty: create characters in Character Forge first, or hit Generate Cast on the Factions page.",
    "安全地带": "Safe zone",
    "尚未设定目的地": "No destination set",
    "局部违常指数": "Local anomaly index",
    "已加入远征队": "Added to expedition party",
    "已至位阶上限": "Already at max tier",
    "已重新组队": "Party reformed",
    "当前委托": "Current contract",
    "成长与经历": "Growth and Experience",
    "报酬": "Reward",
    "无主": "Unclaimed",
    "未知之地": "Unknown land",
    "查看战报（{0} 回合）": "View report ({0} rounds)",
    "生命": "Health",
    "由{0}控制（声望 {1}）": "Controlled by {0} (reputation {1})",
    "目前没有战争": "No wars at the moment",
    "目标地点": "Target location",
    "移出": "Remove",
    "稳定度": "Stability",
    "第 {0} 旬": "Phase {0}",
    "经历": "Experience",
    "经验": "EXP",
    "至少选一名角色": "Select at least one character",
    "行军途中，前往「{0}」": "Marching to「{0}」",
    "补给": "Supply",
    "补给（{0} / 100）": "Supply ({0} / 100)",
    "距「{0}」还需 {1} 旬": "{1} phases to \"{0}\"",
    "距晋升还差 {0} 经验": "{0} EXP to next tier",
    "身上的烙印": "Marks on the body",
    "还剩 {0} 旬": "{0} phases left",
    "还没有发生什么。": "Nothing has happened yet.",
    "还没有成员。": "No members yet.",
    "还没有记录。": "No records yet.",
    "这名角色还没有踏上过远征。": "This character has never been on an expedition.",
    "远征开始！": "Expedition begins!",
    "远征队最多 6 人": "Expedition party max 6 members",
    "选择要加入的角色…": "Select a character to add…",
    "选择角色": "Select character",
    "队伍已经散了": "The party has disbanded",
    "队伍是空的。": "The party is empty.",
    "队伍是空的，无法行动": "The party is empty, cannot act",
    "预计成功率 {0}%": "Estimated success {0}%",
    "额外异化侵蚀：{0}%（计入异化度）": "Extra aberration: {0}% (counts toward aberration)",
    "驻扎于「{0}」": "Stationed at \"{0}\"",
    "（当前位置）": "(current location)",
    "（约 {0} 旬）": "(about {0} phases)",
    "行军": "March",
    "遭遇": "Encounter",
    "战争": "War",
    "外交": "Diplomacy",
    "成长": "Growth"
  };
  for (const k in FRAG) if (!(k in EN)) EN[k] = FRAG[k];
})();
