"use strict";
/* lang-ui2.js — ui2.js display strings EN dictionary fragment. Keys = Chinese display text; values = natural English. First-wins merge into window.__EN. */
(function () {
  const EN = (window.__EN = window.__EN || {});
  const FRAG = {
    "{0}。使用偏好的「{1}」体系，威力 +5%。": "{0}. Uses the preferred \"{1}\" system, power +5%.",
    "{0}。偏好「{1}」体系，你的体系不同，没有加成。": "{0}. Prefers the \"{1}\" system; yours differs, no bonus.",
    "{0}，没有偏好体系。": "{0}, no preferred system.",
    "不隶属任何势力，没有额外加成。": "Belongs to no faction, no bonus.",
    "与": "&",
    "世界旋钮 + 该地偏移": "World dials + local offset",
    "两支小队都至少需要 1 名成员": "Both squads need at least 1 member",
    "个势力": "factions",
    "乙队": "Squad B",
    "乙队明显占优。": "Squad B clearly has the advantage.",
    "乙队胜率": "Squad B win rate",
    "人": "members",
    "人存活": "alive",
    "位阶": "Tier",
    "倒下": "Down",
    "偏好体系": "Preferred system",
    "偏移": "Offset",
    "全队生存率": "Party survival rate",
    "共": "Total",
    "共造成": "dealt",
    "关系类型": "Relation type",
    "击倒": "Knockdowns",
    "删除": "Delete",
    "删除地点": "Delete location",
    "删除这个势力": "Delete this faction",
    "删除这条关系": "Delete this relation",
    "加入": "Add",
    "势力": "Faction",
    "势力关系": "Faction relations",
    "势力最多 14 个": "Faction cap: 14",
    "势力档案": "Faction file",
    "势力等级": "Faction level",
    "双方同时倒下，或势均力敌。": "Both sides fall at once, or it's a dead heat.",
    "取消高亮": "Clear highlight",
    "同一战场、同样的两队，另外模拟 200 场": "Same battlefield, same two squads, simulating 200 more matches",
    "名册中有": "Roster has",
    "名册已满（30 个），请先删除一些": "Roster is full (30); delete some first",
    "名册里至少要有两名角色才能建立关系。可以在角色工坊里存入角色，或点左侧的「一键生成群像」。": "Relations need at least two characters in the roster. Save characters in Character Forge, or click \"Generate Cast\" on the left.",
    "名成员": "members",
    "名称": "Name",
    "回合": "rounds",
    "回合分出胜负": "rounds to decide the winner",
    "回合耗尽，按全队剩余状态判定。": "Rounds exhausted; outcome by remaining party state.",
    "在此推演": "Simulate here",
    "地图上还没有地点，点「新增地点」。": "No locations on the map yet; click \"Add Location\".",
    "地点最多 16 个": "Location cap: 16",
    "地点档案": "Location file",
    "外圈红弧 = 局部违常指数，色晕 = 控制势力，右上数字 = 驻扎角色": "Outer red arc = local anomaly index, halo = controlling faction, top-right number = garrisoned characters",
    "存活": "Alive",
    /* Fragments below are split concatenations used in aria-labels:
       t("对") + name + t("的态度") => "attitude toward <name>",
       t("由") + name + t("控制")   => "controlled by <name>". */
    "对": "attitude toward",
    "对其他势力的态度": "Attitude toward other factions",
    "对异常的态度": "Attitude toward anomaly",
    "对方全员倒下或被现实抹去。": "The entire enemy party is down or erased.",
    "小队最多 5 人": "Squad max 5",
    "局部异象": "Local phenomena",
    "局部法则": "Local laws",
    "局部违常指数": "Local anomaly index",
    "已删除势力": "Faction deleted",
    "已删除地点": "Location deleted",
    "已加入 ${cast.length} 名角色，新增 ${extra.length} 条关系": "Added ${cast.length} characters and ${extra.length} new relations",
    "已加入{0}": "Added to {0}",
    "已建立关系": "Relation established",
    "已按当前世界重新生成地图": "Map regenerated from the current world",
    "已新增势力：": "Faction added:",
    "已新增地点：": "Location added:",
    "已补全 {0} 条关系": "Filled in {0} relations",
    "平均": "Average",
    "平均位阶": "Average tier",
    "平局": "Draw",
    "建立关系": "Build relation",
    "当前工坊角色": "Current forge character",
    "微调局部偏移": "Fine-tune local offset",
    "总部": "Headquarters",
    "恢复类型默认偏移": "Restore type default offset",
    "成员使用「{0}」体系时，威力 +5%。": "When a member uses the \"{0}\" system, power +5%.",
    "战场": "Battlefield",
    "战报": "Battle report",
    "按势力填入（取名册中的成员）": "Fill by faction (from roster members)",
    "控制": "",
    "控制势力": "Controlling faction",
    "无": "None",
    "无人控制": "Uncontrolled",
    "无偏好": "No preference",
    "无所属势力": "No faction",
    "无（在角色工坊里设置「驻地」）": "None (set \"Post\" in Character Forge)",
    "最高输出": "Most damage",
    "未指定": "Unspecified",
    "条": "relations",
    "每人取生命与稳定度中较低者，再对全队取平均": "Each member's lower of health and stability, averaged across the party",
    "没有偏好体系，成员没有额外加成。": "No preferred system; members get no bonus.",
    "没有其他地点。": "No other locations.",
    "没有可以补全的关系了": "No relations left to fill",
    "治疗": "Healing",
    "清空": "Clear",
    "点伤害": "damage",
    "点击切换是否与本地相连": "Click to toggle connection to this location",
    "理念": "Ideals",
    "生命": "Health",
    "由": "controlled by",
    "甲队": "Squad A",
    "甲队明显占优。": "Squad A clearly has the advantage.",
    "甲队胜率": "Squad A win rate",
    "的态度": "",
    "移出": "Remove",
    "移出小队": "Remove from squad",
    "稳定度": "Stability",
    "类型": "Type",
    "胜率估算": "Win-rate estimate",
    "自动补全关系": "Auto-fill relations",
    "至少保留一个势力": "Keep at least one faction",
    "至少保留一个地点": "Keep at least one location",
    "获胜": "Wins",
    "蓝线为甲队行动，红线为乙队行动": "Blue line = Squad A actions, red line = Squad B actions",
    "被抹去": "Erased",
    "角色": "Character",
    "角色乙": "Character B",
    "角色关系": "Character relations",
    "角色甲": "Character A",
    "请先选择要加入的角色": "Pick a character to add first",
    "请选择两名不同的角色": "Pick two different characters",
    "路线与驻扎": "Routes & Garrisons",
    "输出": "Dealt",
    "还没有关系。": "No relations yet.",
    "还没有其他势力。": "No other factions yet.",
    "还没有势力。": "No factions yet.",
    "还没有成员。": "No members yet.",
    "这个势力的成员都在另一支小队里了": "This faction's members are all in the other squad",
    "这名角色已经在某支小队中": "This character is already in a squad",
    "这是一场势均力敌的对局。": "A closely matched battle.",
    "违常指数": "Anomaly Index",
    "选择势力…": "Select faction…",
    "选择成员": "Pick members",
    "选择或新增一个势力。": "Select or create a faction.",
    "选择要加入的角色…": "Pick a character to add…",
    "随机名": "Random name",
    "随机生成一名": "Generate one random",
    "随机补到 4 人": "Randomly fill to 4",
    "隶属": "Affiliation",
    "驻扎角色": "Garrisoned characters",
    "默契": "Synergy"
  };
  for (const k in FRAG) if (!(k in EN)) EN[k] = FRAG[k];
})();
